analytics.integration.enable=true
analytics.team="{\\n  \\"id\\"\: 62753,\\n  \\"role\\"\: \\"OWNER\\",\\n  \\"name\\"\: \\"My Team\\",\\n  \\"organization\\"\: {\\n    \\"id\\"\: 124730,\\n    \\"name\\"\: \\"Organization richardnicolaus01\\",\\n    \\"quotaKSE\\"\: 0,\\n    \\"quotaUnlimitedKSE\\"\: 0,\\n    \\"accountId\\"\: 124730\\n  }\\n}"
analytics.project="{\\n  \\"id\\"\: 75249,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 62753,\\n  \\"status\\"\: \\"ACTIVE\\",\\n  \\"isSampleProject\\"\: false\\n}"
analytics.testresult.autosubmit=true
